### ISSUE TITLE
utilisation de sudo?

### ISSUE THREAD

**Issue by fareschelloug** [mcorbin/exemple-infra#1]
bonjour j'ai regardé attentivement les fichiers et le template .

la méthode utilisée est sympa cependant il faut bien passer le password ?

` "execute_command": "chmod +x {{.Path}}; sudo {{.Path}}",`

**Comment by mcorbin** [comment]
Salut,

Pas besoin car l'utilisateur debian peut sudo sans password.
Il y a plus d'infos dans https://mcorbin.fr/posts/2019-11-21-exemple-infra-vm-image/ et https://www.youtube.com/watch?v=ybSZ2iPF30A

**Comment by fareschelloug** [comment]
merci pour les informations, à la différence je n'utilise pas j'utilise vsphere iso.
je suis obliger de rajouter deux choses : 
"ssh_pty": "true", au niveau du builder et dans le preseed late commands echo 'debian ALL=(ALL) NOPASSWD: ALL' >> /target/etc/sudoers.d/debian ; \
